version: "3"

services:
  db_api:
    container_name: db_api_trib
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports: 
      - "5432:5432"
    volumes: 
      - pgdata:/var/lib/postgresql/data    
volumes:
  pgdata: {}
